// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ApplyUpdateAndRestart():Promise<string>;

export function CancelLogin():Promise<void>;

export function CheckUpdate():Promise<model.UpdateCheckResult>;

export function CheckUpdateOnStartup():Promise<model.UpdateCheckResult>;

export function CheckinAll():Promise<Array<model.CheckinResult>>;

export function CheckinNow(arg1:string):Promise<model.CheckinResult>;

export function CheckinSummary():Promise<model.CheckinSummary>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DownloadAndApplyUpdate():Promise<string>;

export function GetSettings():Promise<model.Settings>;

export function GetVersion():Promise<string>;

export function HasAccounts():Promise<boolean>;

export function ListAccounts():Promise<Array<model.AccountView>>;

export function LoginStatus():Promise<model.LoginStatus>;

export function OpenAuthURL(arg1:string):Promise<void>;

export function OpenDataDir():Promise<void>;

export function PendingUpdateInfo():Promise<model.PendingUpdateInfo>;

export function RefreshQuota(arg1:string):Promise<model.QuotaView>;

export function SaveSettings(arg1:model.Settings):Promise<void>;

export function StartLogin():Promise<model.LoginStart>;

export function UpdateProgress():Promise<model.UpdateDownloadEvent>;
