// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdateAndRestart() {
  return window['go']['main']['App']['ApplyUpdateAndRestart']();
}

export function CancelLogin() {
  return window['go']['main']['App']['CancelLogin']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CheckinAll() {
  return window['go']['main']['App']['CheckinAll']();
}

export function CheckinNow(arg1) {
  return window['go']['main']['App']['CheckinNow'](arg1);
}

export function CheckinSummary() {
  return window['go']['main']['App']['CheckinSummary']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DownloadAndApplyUpdate() {
  return window['go']['main']['App']['DownloadAndApplyUpdate']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasAccounts() {
  return window['go']['main']['App']['HasAccounts']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function LoginStatus() {
  return window['go']['main']['App']['LoginStatus']();
}

export function OpenAuthURL(arg1) {
  return window['go']['main']['App']['OpenAuthURL'](arg1);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function PendingUpdateInfo() {
  return window['go']['main']['App']['PendingUpdateInfo']();
}

export function ProxyStatus() {
  return window['go']['main']['App']['ProxyStatus']();
}

export function RefreshQuota(arg1) {
  return window['go']['main']['App']['RefreshQuota'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetActiveCredential(arg1) {
  return window['go']['main']['App']['SetActiveCredential'](arg1);
}

export function SetProxyEnabled(arg1) {
  return window['go']['main']['App']['SetProxyEnabled'](arg1);
}

export function StartLogin() {
  return window['go']['main']['App']['StartLogin']();
}

export function UpdateProgress() {
  return window['go']['main']['App']['UpdateProgress']();
}
