// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelLogin() {
  return window['go']['main']['App']['CancelLogin']();
}

export function CheckinAll() {
  return window['go']['main']['App']['CheckinAll']();
}

export function CheckinNow(arg1) {
  return window['go']['main']['App']['CheckinNow'](arg1);
}

export function CheckinSummary() {
  return window['go']['main']['App']['CheckinSummary']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasAccounts() {
  return window['go']['main']['App']['HasAccounts']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function LoginStatus() {
  return window['go']['main']['App']['LoginStatus']();
}

export function OpenAuthURL(arg1) {
  return window['go']['main']['App']['OpenAuthURL'](arg1);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function RefreshQuota(arg1) {
  return window['go']['main']['App']['RefreshQuota'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartLogin() {
  return window['go']['main']['App']['StartLogin']();
}
